[package]
name = "astreon"
description = "Batteries-included retained-mode desktop UI framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["editor"]
editor = ["dep:astreon-editor"]
testing = ["dep:astreon-testing"]

[dependencies]
astreon-app = { workspace = true }
astreon-editor = { workspace = true, optional = true }
astreon-native-menu = { workspace = true }
astreon-testing = { workspace = true, optional = true }
astreon-widgets = { workspace = true }
astrelis-ui = { workspace = true }

[dev-dependencies]
astrelis-app = { workspace = true }
astrelis-core = { workspace = true }
astrelis-platform = { workspace = true }
astrelis-platform-winit = { workspace = true }
astrelis-text = { workspace = true }
astrelis-ui-core = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
