[package]
name = "astreon-editor"
description = "Editor workspace components for Astreon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
astreon-app = { workspace = true }
astreon-widgets = { workspace = true }
astrelis-ui-docking = { workspace = true }
astrelis-ui-widgets = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true

